FROM ubuntu:latest as base
RUN apt-get update && \
    apt-get install -y curl tar gzip xzip

FROM base
RUN mv /root/.bashrc /root/.bashrc.org && \
    mv /root/.profile /root/.profile.org
COPY launch.sh /root/launch.sh
