
if = '''executable('deno')'''

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
source ~/.config/nvim/config/ddc.vim
'''
[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/pum.vim'


