[[plugins]]
repo = 'Shougo/ddc.vim'
if = '''dein#is_available('denops')'''
hook_add = '''
if dein#is_available('denops')
  source ~/.config/nvim/config/ddc.vim
endif
'''

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
if = '''dein#is_available('ddc')'''

[[plugins]]
repo = 'Shougo/ddc-around'
if = '''dein#is_available('ddc')'''

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
if = '''dein#is_available('ddc')'''

[[plugins]]
repo = 'LumaKernel/ddc-file'
if = '''dein#is_available('ddc')'''

[[plugins]]
repo = 'Shougo/pum.vim'
if = '''dein#is_available('ddc')'''

