
function get_arch() {
    echo "${lightblueb}$(uname -m)${end}"
}

function face_input(){
     local saveExit=$?
     #echo "test ${saveExit}"
     if [[ ${saveExit} != 0 ]] ;then
        echo -e "${red}0-0${end}"
     else
        echo -e "${yellow}^-^${end}"
     fi
     #echo -e ${g_face}
}

function username_host() {
    if [ $(id -u) != 0 ];then
        echo -e "${green}\u${end}@${yellow}\h${end}"
    else
        echo -e "${red}\u${end}@${yellow}\h${end}"
    fi
}

function git_info() {
  # check if we're in a git repo
  git rev-parse --is-inside-work-tree &>/dev/null || return

  # quickest check for what branch we're on
  branch=$(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')

  # check if it's dirty (via github.com/sindresorhus/pure)
  dirty=$(git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ]&& echo -e "*")

  echo -e "${end} on ${purple}${branch}${dirty}${end}"
}

if [ "$color_prompt" = yes ]; then
    PS1='$(face_input)'" \w ${OS} $(username_host)/$(get_arch)"'$(git_info)'" \$ "
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi

unset color_prompt force_color_prompt