export GOROOT=$HOME/.local/go
export GOPATH=$HOME/.local/gobin
export DENO_INSTALL="/home/atolycs/.deno"
if [[ "$(uname -r)" == *microsoft* ]];then
  export WIN32YANK="/mnt/c/run/win32yank-x64"
  export PATH=$PATH:$WIN32YANK
fi

export ORIGINAL_PATH="${DENO_INSTALL}/bin:${GOROOT}/bin:${GOPATH}/bin"

export PATH=${ORIGINAL_PATH}:$HOME/.local/bin:$HOME/.nodebrew/current/bin:$PATH

# cheat module
export CHEAT_CONFIG_PATH="~/.config/cheat/conf.yml"
