# This script is respect for https://korosuke613.hatenablog.com/entry/2021/05/23/mydotfiles

# Thank you @korosuke613

if test -n "$(git -C \"${DOT_MAIN}\" status --porcelain)" ||
   ! git -C \"${DOT_MAIN}\" diff --exit-code --stat --cached origin/main > /dev/null ; then
  echo -e "\e[36m=== DOTFILES IS DIRTY ===\e[m"
  echo -e "\e[33mThe dotfiles have been changed.\e[m"
  echo -e "\e[33mPlease update them with the following command.\e[m"
  echo "  cd ${DOT_MAIN}"
  echo "  git add ."
  echo "  git commit -m \"update dotfiles\""
  echo "  git push origin main"
  echo -e "\e[33mor\e[m"
  echo "  git push origin main"
  echo -e "\e[36m=========================\e[m"
fi
