name: Test Run

on:
  push:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Env setup
        run: | 
          mv ~/.bashrc ~/.bashrc.org
          mv ~/.profile ~/.profile.org

      - uses: actions/checkout@v2

      - name: Run link.sh
        run: bash ${GITHUB_WORKSPACE}/bin/link.sh
      
      - name: Load .bashrc
        run: |
          bash ~/.bashrc
